
language: bash

install: ./install-dependencies.sh

script:
  - export PATH="$HOME/miniconda/bin:$PATH" 
  - ./build
  - zip -r slides.zip slides.html reveal.js-3.5.0
  - curl --upload-file slides.zip https://transfer.sh/slides.zip
